import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import SideBar from "@/components/SideBar";
import { Cairo } from "next/font/google";

const cario = Cairo({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`h-screen w-screen flex ${cario.className}`}>
        <Providers>
          <div className="flex h-screen w-screen text-white">
            <div className="hidden lg:flex h-full w-[16rem] flex-col gap-y-5 overflow-y-auto">
              <SideBar />
            </div>
            <main className="h-screen w-full overflow-hidden">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
